#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MaterialLoadingProgressbarCSharp.Resource", IsApplication=false)]

namespace MaterialLoadingProgressbarCSharp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public static int mlpb_arrow_height = 2130771975;
			
			// aapt resource value: 0x7f010006
			public static int mlpb_arrow_width = 2130771974;
			
			// aapt resource value: 0x7f010001
			public static int mlpb_background_color = 2130771969;
			
			// aapt resource value: 0x7f010005
			public static int mlpb_enable_circle_background = 2130771973;
			
			// aapt resource value: 0x7f010000
			public static int mlpb_inner_radius = 2130771968;
			
			// aapt resource value: 0x7f010009
			public static int mlpb_max = 2130771977;
			
			// aapt resource value: 0x7f010008
			public static int mlpb_progress = 2130771976;
			
			// aapt resource value: 0x7f010002
			public static int mlpb_progress_color = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int mlpb_progress_stoke_width = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public static int mlpb_progress_text_color = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public static int mlpb_progress_text_size = 2130771978;
			
			// aapt resource value: 0x7f01000c
			public static int mlpb_progress_text_visibility = 2130771980;
			
			// aapt resource value: 0x7f010004
			public static int mlpb_show_arrow = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f020001
			public static int invisible = 2130837505;
			
			// aapt resource value: 0x7f020000
			public static int visible = 2130837504;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public static int ApplicationName = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircleProgressBar = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 7
			public static int CircleProgressBar_mlpb_arrow_height = 7;
			
			// aapt resource value: 6
			public static int CircleProgressBar_mlpb_arrow_width = 6;
			
			// aapt resource value: 1
			public static int CircleProgressBar_mlpb_background_color = 1;
			
			// aapt resource value: 5
			public static int CircleProgressBar_mlpb_enable_circle_background = 5;
			
			// aapt resource value: 0
			public static int CircleProgressBar_mlpb_inner_radius = 0;
			
			// aapt resource value: 9
			public static int CircleProgressBar_mlpb_max = 9;
			
			// aapt resource value: 8
			public static int CircleProgressBar_mlpb_progress = 8;
			
			// aapt resource value: 2
			public static int CircleProgressBar_mlpb_progress_color = 2;
			
			// aapt resource value: 3
			public static int CircleProgressBar_mlpb_progress_stoke_width = 3;
			
			// aapt resource value: 11
			public static int CircleProgressBar_mlpb_progress_text_color = 11;
			
			// aapt resource value: 10
			public static int CircleProgressBar_mlpb_progress_text_size = 10;
			
			// aapt resource value: 12
			public static int CircleProgressBar_mlpb_progress_text_visibility = 12;
			
			// aapt resource value: 4
			public static int CircleProgressBar_mlpb_show_arrow = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
