#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SampleActivity.Resource", IsApplication=true)]

namespace SampleActivity
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MaterialLoadingProgressbarCSharp.Resource.Attribute.mlpb_arrow_height = global::SampleActivity.Resource.Attribute.mlpb_arrow_height;
			global::MaterialLoadingProgressbarCSharp.Resource.Attribute.mlpb_arrow_width = global::SampleActivity.Resource.Attribute.mlpb_arrow_width;
			global::MaterialLoadingProgressbarCSharp.Resource.Attribute.mlpb_background_color = global::SampleActivity.Resource.Attribute.mlpb_background_color;
			global::MaterialLoadingProgressbarCSharp.Resource.Attribute.mlpb_enable_circle_background = global::SampleActivity.Resource.Attribute.mlpb_enable_circle_background;
			global::MaterialLoadingProgressbarCSharp.Resource.Attribute.mlpb_inner_radius = global::SampleActivity.Resource.Attribute.mlpb_inner_radius;
			global::MaterialLoadingProgressbarCSharp.Resource.Attribute.mlpb_max = global::SampleActivity.Resource.Attribute.mlpb_max;
			global::MaterialLoadingProgressbarCSharp.Resource.Attribute.mlpb_progress = global::SampleActivity.Resource.Attribute.mlpb_progress;
			global::MaterialLoadingProgressbarCSharp.Resource.Attribute.mlpb_progress_color = global::SampleActivity.Resource.Attribute.mlpb_progress_color;
			global::MaterialLoadingProgressbarCSharp.Resource.Attribute.mlpb_progress_stoke_width = global::SampleActivity.Resource.Attribute.mlpb_progress_stoke_width;
			global::MaterialLoadingProgressbarCSharp.Resource.Attribute.mlpb_progress_text_color = global::SampleActivity.Resource.Attribute.mlpb_progress_text_color;
			global::MaterialLoadingProgressbarCSharp.Resource.Attribute.mlpb_progress_text_size = global::SampleActivity.Resource.Attribute.mlpb_progress_text_size;
			global::MaterialLoadingProgressbarCSharp.Resource.Attribute.mlpb_progress_text_visibility = global::SampleActivity.Resource.Attribute.mlpb_progress_text_visibility;
			global::MaterialLoadingProgressbarCSharp.Resource.Attribute.mlpb_show_arrow = global::SampleActivity.Resource.Attribute.mlpb_show_arrow;
			global::MaterialLoadingProgressbarCSharp.Resource.Id.invisible = global::SampleActivity.Resource.Id.invisible;
			global::MaterialLoadingProgressbarCSharp.Resource.Id.visible = global::SampleActivity.Resource.Id.visible;
			global::MaterialLoadingProgressbarCSharp.Resource.String.ApplicationName = global::SampleActivity.Resource.String.ApplicationName;
			global::MaterialLoadingProgressbarCSharp.Resource.Styleable.CircleProgressBar = global::SampleActivity.Resource.Styleable.CircleProgressBar;
			global::MaterialLoadingProgressbarCSharp.Resource.Styleable.CircleProgressBar_mlpb_arrow_height = global::SampleActivity.Resource.Styleable.CircleProgressBar_mlpb_arrow_height;
			global::MaterialLoadingProgressbarCSharp.Resource.Styleable.CircleProgressBar_mlpb_arrow_width = global::SampleActivity.Resource.Styleable.CircleProgressBar_mlpb_arrow_width;
			global::MaterialLoadingProgressbarCSharp.Resource.Styleable.CircleProgressBar_mlpb_background_color = global::SampleActivity.Resource.Styleable.CircleProgressBar_mlpb_background_color;
			global::MaterialLoadingProgressbarCSharp.Resource.Styleable.CircleProgressBar_mlpb_enable_circle_background = global::SampleActivity.Resource.Styleable.CircleProgressBar_mlpb_enable_circle_background;
			global::MaterialLoadingProgressbarCSharp.Resource.Styleable.CircleProgressBar_mlpb_inner_radius = global::SampleActivity.Resource.Styleable.CircleProgressBar_mlpb_inner_radius;
			global::MaterialLoadingProgressbarCSharp.Resource.Styleable.CircleProgressBar_mlpb_max = global::SampleActivity.Resource.Styleable.CircleProgressBar_mlpb_max;
			global::MaterialLoadingProgressbarCSharp.Resource.Styleable.CircleProgressBar_mlpb_progress = global::SampleActivity.Resource.Styleable.CircleProgressBar_mlpb_progress;
			global::MaterialLoadingProgressbarCSharp.Resource.Styleable.CircleProgressBar_mlpb_progress_color = global::SampleActivity.Resource.Styleable.CircleProgressBar_mlpb_progress_color;
			global::MaterialLoadingProgressbarCSharp.Resource.Styleable.CircleProgressBar_mlpb_progress_stoke_width = global::SampleActivity.Resource.Styleable.CircleProgressBar_mlpb_progress_stoke_width;
			global::MaterialLoadingProgressbarCSharp.Resource.Styleable.CircleProgressBar_mlpb_progress_text_color = global::SampleActivity.Resource.Styleable.CircleProgressBar_mlpb_progress_text_color;
			global::MaterialLoadingProgressbarCSharp.Resource.Styleable.CircleProgressBar_mlpb_progress_text_size = global::SampleActivity.Resource.Styleable.CircleProgressBar_mlpb_progress_text_size;
			global::MaterialLoadingProgressbarCSharp.Resource.Styleable.CircleProgressBar_mlpb_progress_text_visibility = global::SampleActivity.Resource.Styleable.CircleProgressBar_mlpb_progress_text_visibility;
			global::MaterialLoadingProgressbarCSharp.Resource.Styleable.CircleProgressBar_mlpb_show_arrow = global::SampleActivity.Resource.Styleable.CircleProgressBar_mlpb_show_arrow;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int mlpb_arrow_height = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int mlpb_arrow_width = 2130771974;
			
			// aapt resource value: 0x7f010001
			public const int mlpb_background_color = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int mlpb_enable_circle_background = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int mlpb_inner_radius = 2130771968;
			
			// aapt resource value: 0x7f010009
			public const int mlpb_max = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int mlpb_progress = 2130771976;
			
			// aapt resource value: 0x7f010002
			public const int mlpb_progress_color = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int mlpb_progress_stoke_width = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int mlpb_progress_text_color = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int mlpb_progress_text_size = 2130771978;
			
			// aapt resource value: 0x7f01000c
			public const int mlpb_progress_text_visibility = 2130771980;
			
			// aapt resource value: 0x7f010004
			public const int mlpb_show_arrow = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int activity_vertical_margin = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040001
			public const int invisible = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int progress1 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int progress2 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int progressWithArrow = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int progressWithoutBg = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int visible = 2130968576;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Hello = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircleProgressBar = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 7
			public const int CircleProgressBar_mlpb_arrow_height = 7;
			
			// aapt resource value: 6
			public const int CircleProgressBar_mlpb_arrow_width = 6;
			
			// aapt resource value: 1
			public const int CircleProgressBar_mlpb_background_color = 1;
			
			// aapt resource value: 5
			public const int CircleProgressBar_mlpb_enable_circle_background = 5;
			
			// aapt resource value: 0
			public const int CircleProgressBar_mlpb_inner_radius = 0;
			
			// aapt resource value: 9
			public const int CircleProgressBar_mlpb_max = 9;
			
			// aapt resource value: 8
			public const int CircleProgressBar_mlpb_progress = 8;
			
			// aapt resource value: 2
			public const int CircleProgressBar_mlpb_progress_color = 2;
			
			// aapt resource value: 3
			public const int CircleProgressBar_mlpb_progress_stoke_width = 3;
			
			// aapt resource value: 11
			public const int CircleProgressBar_mlpb_progress_text_color = 11;
			
			// aapt resource value: 10
			public const int CircleProgressBar_mlpb_progress_text_size = 10;
			
			// aapt resource value: 12
			public const int CircleProgressBar_mlpb_progress_text_visibility = 12;
			
			// aapt resource value: 4
			public const int CircleProgressBar_mlpb_show_arrow = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
